### PR TITLE
Api v3

### PR DESCRIPTION
**Pull request by cerberillo**
New Library working along with API v3 requirements.

It includes:

* API v3 usage
* Click caching
* Multiple beacon confirmation (both url and javascript ones)
* New visibility tracker to ensure IAB conditions
* Usage of WebView UA in all outcoming connections.

### CODE REVIEW

**Comment by RagnarR** [comment]
👍

**Comment by cerberillo** [comment]
waiting for QA before merging

**Comment by cerberillo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ORURPDoE&#x2F;1173-15-rewrite-ios-library-to-support-api-v3-18"> (15) Rewrite iOS library to support API v3 [18]</a>

**Comment by cerberillo** [comment]
Approved by QA

**Pull request merged**
